#+AUTHOR: Noemi
#+TITLE: Emacs Config

* Package Management System
** use-package
  #+begin_src emacs-lisp

	 (require 'package)

	 ;; Nice macro for updating lists in place.
	 (defmacro append-to-list (target suffix)
		"Append SUFFIX to TARGET in place."
		`(setq ,target (append ,target ,suffix)))

	 ;; setup emacs package archives
	 (append-to-list package-archives
			 '(("melpa" . "http://melpa.org/packages/") ;; Main package archive
				("melpa-stable" . "http://stable.melpa.org/packages/") ;; Some packages might only do stable releases?
				("org-elpa" . "https://orgmode.org/elpa/"))) ;; Org packages, I don't use org but seems like a harmless default

	 (package-initialize)

			;; Ensure use-package is present. From here on out, all packages are loaded
			;; with use-package, a macro for importing and installing packages. Also, refresh the package archive on load so we can pull the latest packages.
			(unless (package-installed-p 'use-package)
			  (package-refresh-contents)
			  (package-install 'use-package))

  #+end_src

** automatic package update
  #+begin_src emacs-lisp

	 (use-package auto-package-update
      :ensure t
		:custom
		(auto-package-update-interval 7)
		(auto-package-update-prompt-before-update t)
		(auto-package-update-hide-results t)
		:config
		(auto-package-update-maybe)
		(auto-package-update-at-time "09:00"))

  #+end_src
  
 
* Preferences
** shell
	#+begin_src emacs-lisp
	  ; (setq explicit-shell-file-name "C:\\Windows\\System32\\WindowsPowershell\\v1.0\\powershell.exe")
	  ; (setq explicit-powershell.exe-args '("-Command" "-" )) ; interactive but no command prompt
     (setq comint-completion-addsuffix (quote ("\\" . " ")))
	#+end_src


* Basic UI Configuration
  #+begin_src emacs-lisp

	 ;; start on the "dashboard" buffer
	 (setq inhibit-startup-message t)

	 ;; disables bell sound... very annoying
	 (setq visible-bell t)

	 ;; maximized window at start
	 (toggle-frame-maximized)

	 ;; line numbers
	 (visual-line-mode)
	 (global-hl-line-mode)
	 (setq-default truncate-lines t)

	 (column-number-mode)
	 (global-display-line-numbers-mode t)

	 ;; disables line numbers for some modes
	 (dolist (mode '(org-mode-hook
                    lsp-treemacs-mode-hook
						  term-mode-hook
						  eshell-mode-hook))
				(add-hook mode (lambda () (display-line-numbers-mode 0)))
	 )

	 ;; clear emacs ui
	 (scroll-bar-mode -1)
	 (tool-bar-mode -1)
	 (tooltip-mode -1)
	 (menu-bar-mode -1)
	 (set-fringe-mode 0) ;; set "borders" to 0px

  #+end_src


* Keybindings

** evil-mode
	#+begin_src emacs-lisp

	  ;; Evil-mode (truly a life changer)
	  (use-package evil
		 :ensure t ;; install if not already installed
		 :init     ;; start configuration
		 (setq evil-want-integration t) ;; set to t by default
		 (setq evil-want-keybinding nil)
		 (setq evil-vsplit-window-right t)
		 (setq evil-split-window-below t)
		 (evil-mode))

	  (use-package evil-collection
		 :after evil
		 :ensure t
		 :config
       (setq evil-want-keybinding nil)
		 (evil-collection-init))

	  (use-package evil-nerd-commenter
		  :ensure t
		  :after evil
		  :bind ("M-/" . evilnc-comment-or-uncomment-lines)
	  )

	#+end_src


** others
	#+begin_src emacs-lisp

	  ;; (global-set-key (kbd "C-h") 'evil-window-left)
	  ;; (global-set-key (kbd "C-j") 'evil-window-down)
	  ;; (global-set-key (kbd "C-k") 'evil-window-up)
	  ;; (global-set-key (kbd "C-l") 'evil-window-right)

	#+end_src

	
* UI Enhancement
** color theme
	#+begin_src emacs-lisp

	  (load-theme 'doom-one)

	#+end_src
** modeline
	#+begin_src emacs-lisp

	  ;; use doom modeline
	  (use-package doom-modeline
			:ensure t
			:init (doom-modeline-mode 1)
         :config
				(setq doom-modeline-hud t)
	  )

	#+end_src
** font face
	#+begin_src emacs-lisp

	  (set-face-attribute 'default nil :font "Cascadia Code Semibold" :height 90)

	#+end_src
** icons
** dashboard
	#+begin_src emacs-lisp

	  (use-package dashboard
			:ensure t
			:init
			:config
				(setq dashboard-center-content t)
				(dashboard-setup-startup-hook)
				(setq dashboard-startup-banner 3) ;; set 3rd text logo from the package
				(setq dashboard-items '((recents  . 5)
					 (bookmarks . 5)
					 (projects . 5)
					 (agenda . 5)
					 (registers . 5)))
				(setq dashboard-set-heading-icons t)
				(setq dashboard-set-file-icons t)
				;; prettier icons
				(dashboard-modify-heading-icons '((recents . "file-text")
					 (bookmarks . "book")))
	  )

	 #+end_src
** which key
	#+begin_src emacs-lisp

     ;; which key
	  (use-package which-key
		  :ensure t
		  :init (which-key-mode)
	  )

	#+end_src
** Ivy and Counsel
	#+begin_src emacs-lisp

		;; idk
		(use-package ivy
     :ensure t
	  :diminish
	  :bind (("C-s" . swiper)
	  :map ivy-minibuffer-map
			("TAB" . ivy-alt-done)
			("C-l" . ivy-alt-done)
			("C-j" . ivy-next-line)
			("C-k" . ivy-previous-line)
	  :map ivy-switch-buffer-map
			("C-k" . ivy-previous-line)
			("C-l" . ivy-done)
			("C-d" . ivy-switch-buffer-kill)
	  :map ivy-reverse-i-search-map
			("C-k" . ivy-previous-line)
			("C-d" . ivy-reverse-i-search-kill))
	  :config
	  (ivy-mode 1))

		;; pairs with ivy for better emacs interactions
		(use-package counsel :ensure t)

	#+end_src


* Editing Preferences
  #+begin_src emacs-lisp

	 (setq-default tab-width 3)
	 (electric-pair-mode)

  #+end_src

 
* Org Mode

  #+begin_src emacs-lisp

    (defun dw/org-mode-setup ()
      (org-indent-mode)
      (variable-pitch-mode 0)
      (auto-fill-mode 0)
      (visual-line-mode 1)
      (setq evil-auto-indent nil))

     (use-package org
       :ensure t
       :hook (org-mode . dw/org-mode-setup)
       :config (setq org-ellipsis " ▼"
                org-hide-emphasis-markers t)
     )
     (use-package org-bullets
       :ensure t
       :hook (org-mode . org-bullets-mode)
       :custom
         (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●"))
     )

  #+end_src

** appearence
*** font faces
*** heading bullets
*** center buffer


** config


* Development

** lsp mode

	LSP stands for Language Server Protocol, and provides language support via communication with
	an external server.

	In order to get code completion, you need to have installed both a language server and a mode for
	the specific language. LSP interacts with the server installed, while emacs uses the mode installed
	as a front-end.

	So you basically need:
	- a backend : e.g. LSP
	- a frontend : rust-mode
	- a server : rust-analyzer

	NOTE: the kybinding <C-c l> is only a custom prefix, it's not a command.
	      (with ivy and counsel it will still show the possible commands after you invoke it)

	Check out lsp-ui-doc and lsp-ui-sideline

	#+begin_src emacs-lisp

		(use-package lsp-mode
			 :ensure t
			 :commands (lsp lsp-deferred)
			 :init
			 (setq lsp-keymap-prefix "C-c l")
			 :config
			 (lsp-enable-which-key-integration t)
		)

		(use-package lsp-ui
			 :ensure t
			 :hook (lsp-mode . lsp-ui-mode)
		)

		(use-package lsp-treemacs
			 :ensure t
			 :after lsp
		)

	  (use-package lsp-ivy
			 :ensure t
			 :after lsp
     )

	#+end_src

*** TODO remove lsp-treemacs line numbers

	
** languages

*** Rust
	  #+begin_src emacs-lisp

		 (use-package rust-mode
			 :ensure t
			 :mode "\\.rs\\'"
			 :hook (rust-mode . lsp-deferred)
          :config
				 (setq rust-format-on-save t)
		 )

	  #+end_src

*** C/C++
	 #+begin_src emacs-lisp
      (use-package cmake-mode :ensure t)

		(use-package ccls
		  :ensure t
		  :hook ((c-mode c++-mode objc-mode) . (lambda () (require 'ccls) (lsp)))
		  :config
			 (setq ccls-executable "ccls")
		)

		;; something idk
		(setq lsp-clangd-binary-path "C:\\Program Files\\LLVM\\bin\\clangd.exe")

	 #+end_src


** preferences
	#+begin_src emacs-lisp
	  (c-set-offset 'substatement-open 0)
	  (c-set-offset 'innamespace 0)
	  (c-set-offset 'brace-list-open 0)
	  (setq c-basic-offset 4)
	#+end_src


** company mode

	 NOTE: use <C-j> and <C-k> to move in the completions box
	 
	 #+begin_src emacs-lisp

		(use-package company
			:ensure t
			:after lsp-mode
			:hook (lsp-mode . copmany-mode)
			:bind (:map company-active-map
					;; use tab to complete suggested copmletion instead of cycling through entries
					 ("<tab>" . company-complete-selection))
					(:map lsp-mode-map
					 ("<tab>" . company-indent-or-complete-common))
			:custom
         ;; completions starts as soon as you type 1 char, and after 0.0 seconds of delay
			(company-minimum-prefix-length 1)
			(company-idle-delay 0.0)
		)

		(use-package company-box
			:ensure t
			:hook (company-mode . company-box-mode)
		)

	 #+end_src
